# Generated by Django 2.2.12 on 2020-12-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mathematics',
        ),
    ]
