# Generated by Django 2.2.12 on 2021-01-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
