# Generated by Django 2.2.12 on 2021-01-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0004_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('upload_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
